name: Publish to pub.dev

on:
  push:
    tags:
      - "publish_[0-9]+.[0-9]+.[0-9]+*"

  workflow_dispatch:

# Publish using custom workflow
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get
      # Here you can insert custom steps you need
      # - run: dart tool/generate-code.dart
      - name: Run All Tests
        run: flutter test
      - name: Publish
        run: flutter pub publish --force
